spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        formate_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

  security:
    oauth2:
      client:
        registration:
          google:
            url: https://accounts.google.com/o/oauth2/v2/auth
            client-id: 392130591847-s96rig57ea8ub5of158r775dlrt7oinf.apps.googleusercontent.com
            client-secret: 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
            callback-url: http://localhost:8080/api/login/auth/google/callback
            scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
          naver:
            url: https://nid.naver.com/oauth2.0/authorize
            client-name: Naver
            client-id: kN65jBm86aZm5f4vVomY
            authorization-grant-type: authorization_code
            client-secret: pRer_HMnz3
            callback-url: http://localhost:8080/api/login/auth/naver/callback


logging:
  level:
    org.hibernate.SQL: debug




#mybatis:
#  type-aliases-package: com.example.appserver.group
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/**/*.xml

#spring.thymeleaf.prefix=classpath:templates/
#spring.thymeleaf.suffix=.html